# Generated by Django 3.1.4 on 2020-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('qual', models.TextField()),
                ('mob', models.IntegerField()),
                ('pname', models.TextField(max_length=100)),
                ('pmob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='image')),
                ('course', models.CharField(max_length=500)),
            ],
        ),
    ]
