# Generated by Django 3.1.4 on 2021-01-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_auto_20201230_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='pname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='qual',
            field=models.CharField(max_length=100),
        ),
    ]
